version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '..'
    schedule:
      interval: 'daily'
      time: '04:30'
    labels:
      - 'javascript'
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'dependa'
    open-pull-requests-limit: 20

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '04:30'
    labels:
      - 'github-actions'
      - 'dependencies'
      - 'dependabot'

    commit-message:
      prefix: 'dependa'
    open-pull-requests-limit: 20
